apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: imroc-crt
  namespace: default
spec:
  secretName: imroc-crt-secret
  issuerRef:
    name: letsencrypt-dns01
    kind: ClusterIssuer
    group: cert-manager.io
  dnsNames:
  - imroc.io
  - cyd.imroc.io
